image: kubeagi/llama-factory:latest
imagePullPolicy: IfNotPresent
resources:
  limits:
    cpu: "4"
    memory: 12Gi
  requests:
    cpu: "1"
    memory: 1Gi

# ingress configurations for component
ingress:
  # set enable to `true` to enable ingress
  enable: true
  ingressClassName: portal-ingress
  ingressDomain: 192.168.0.247.nip.io
